export const bancos = [
    "PAGBANK-PAGSEGURO",
    "XP Investimentos",
    "INTER",
    "BTG PACTUAL/BANCO PAN",
    "C6 BANK",
    "AME DIGITAL",
    "SANTANDER",
    "BRADESCO",
    "CAIXA ECONÔMICA FEDERAL",
    "ITAÚ",
    "MERCADO PAGO",
    "ORIGINAL",
    "NEON",
    "NUBANK",
    "Banco do Brasil S.A.",
    "Banco Santander (Brasil) S.A.",
    "Caixa Econômica Federal",
    "Banco Bradesco S.A.",
    "Itaú Unibanco S.A.",
    "Nu Pagamentos S.A.",
    "Banco C6 S.A.",
    "Banco Inter S.A.",
    "Acesso Soluções De Pagamento S.A.",
    "Advanced Corretora De Câmbio Ltda",
    "Agk Corretora De Cambio S.A.",
    "Al5 S.A. Crédito",
    "Albatross Ccv S.A",
    "Amazónia Corretora De Câmbio Ltda.",
    "Ativa Investimentos S.A. Corretora De Títulos, Câmbio E Valores",
    "Avista S.A. Crédito",
    "B&T Corretora De Cambio Ltda.",
    "Banco Abc Brasil S.A.",
    "Banco Abn Amro S.A.",
    "Banco Agibank S.A.",
    "Banco Alfa S.A.",
    "Banco Alvorada S.A.",
    "Banco Andbank (Brasil) S.A.",
    "Banco Arbi S.A.",
    "Banco B3 S.A.",
    "Banco Bandepe S.A.",
    "Banco Bari De Investimentos E Financiamentos S.A.",
    "Banco BMG S.A.",
    "Banco Bnp Paribas Brasil S.A.",
    "Banco Bocom Bbm S.A.",
    "Banco Bradescard S.A.",
    "Banco Bradesco BBI S.A.",
    "Banco Bradesco Berj S.A.",
    "Banco Bradesco Cartões S.A.",
    "Banco Bradesco Financiamentos S.A.",
    "Banco Bs2 S.A.",
    "Banco BTG Pactual S.A.",
    "Banco C6 Consignado S.A.",
    "Banco Caixa Geral – Brasil S.A.",
    "Banco Capital S.A.",
    "Banco Cargill S.A.",
    "Banco Cedula S.A.",
    "Banco Cetelem S.A.",
    "Banco Citibank S.A.",
    "Banco Classico S.A.",
    "Banco Cooperativo Do Brasil S.A. – Bancoob – Sicoob",
    "Banco Cooperativo Sicredi S.A.",
    "Banco Crédit Agricole Brasil S.A.",
    "Banco Credit Suisse (Brasil) S.A.",
    "Banco Crefisa S.A.",
    "Banco Cresol – Confederação Nacional Das Cooperativas Centrais De Crédito e Economia Familiar e Solidária",
    "Banco CSF S.A.",
    "Banco da Amazonia S.A.",
    "Banco da China Brasil S.A.",
    "Banco Daycoval S.A.",
    "Banco de Desenvolvimento do Espírito Santo S.A.",
    "Banco De La Nacion Argentina",
    "Banco De La Provincia De Buenos Aires",
    "Banco de La Republica Oriental del Uruguay",
    "Banco Digimais S.A.",
    "Banco Digio S.A.",
    "Banco Do Estado De Sergipe S.A.",
    "Banco Do Estado Do Pará S.A.",
    "Banco Do Estado Do Rio Grande Do Sul S.A. (BANRISUL)",
    "Banco Do Nordeste Do Brasil S.A.",
    "Banco Fator S.A.",
    "Banco Fibra S.A.",
    "Banco Finaxis S.A.",
    "Banco Gm S.A.",
    "Banco Guanabara S.A.",
    "Banco HSBC S.A.",
    "Banco Inbursa S.A.",
    "Banco Industrial Do Brasil S.A.",
    "Banco Indusval S.A.",
    "Banco Investcred Unibanco S.A.",
    "Banco Itaú BBA S.A.",
    "Banco Itaú Consignado S.A.",
    "Banco Itaubank S.A.",
    "Banco J. Safra S.A.",
    "Banco J.P. Morgan S.A.",
    "Banco John Deere S.A.",
    "Banco Kdb Do Brasil S.A.",
    "Banco Keb Hana Do Brasil S.A.",
    "Banco Luso Brasileiro S.A.",
    "Banco Master S.A.",
    "Banco RNX",
    "Banco Mercantil do Brasil S.A.",
    "Banco Mercedes-Benz Do Brasil S.A.",
    "Banco Mizuho Do Brasil S.A.",
    "Banco Modal S.A.",
    "Banco Morgan Stanley S.A.",
    "Banco Mufg Brasil S.A.",
    "Banco Nacional De Desenvolvimento Economico E Social",
    "Banco Olé Consignado S.A.",
    "Banco Original Do Agronegócio S.A.",
    "Banco Original S.A.",
    "Banco Ourinvest S.A.",
    "Banco Pan S.A.",
    "Banco Paulista S.A.",
    "Banco Pine S.A.",
    "Banco Rabobank International Brasil S.A.",
    "Banco Randon S.A.",
    "Banco Rendimento S.A.",
    "Banco Ribeirao Preto S.A.",
    "Banco Rodobens S.A.",
    "Banco Safra S.A.",
    "Banco Semear S.A.",
    "Banco Sistema S.A.",
    "Banco Smartbank S.A.",
    "Banco Societe Generale Brasil S.A.",
    "Banco Sofisa S.A.",
    "Banco Sumitomo Mitsui Brasileiro S.A.",
    "Banco Topázio S.A.",
    "Banco Toyota Do Brasil S.A.",
    "Banco Triangulo S.A.",
    "Banco Tricury S.A.",
    "Banco Volkswagen S.A.",
    "Banco Votorantim S.A.",
    "Banco Vr S.A.",
    "Banco Western Union Do Brasil S.A.",
    "Banco Woori Bank Do Brasil S.A.",
    "Banco Xp S.A.",
    "Bancoseguro S.A.",
    "Banestes S.A. Banco Do Estado do Espirito Santo",
    "Bank of America Merrill Lynch Banco Múltiplo S.A.",
    "Bari Companhia Hipotecária",
    "Bbc Leasing S.A. – Arrendamento Mercantil",
    "Bcv – Banco De Crédito E Varejo S.A.",
    "Bexs Banco De Câmbio S/A",
    "Bexs Corretora De Câmbio S/A",
    "Bgc Liquidez Distribuidora De Títulos E Valores Mobiliários Ltda",
    "Bny Mellon Banco S.A.",
    "Bónuscred Sociedade De Crédito Direto S.A.",
    "Bpp Instituição De Pagamento S.A.",
    "Br Partners Banco De Investimento S.A.",
    "BrB – Banco De Brasilia S.A.",
    "Brk S.A. Crédito",
    "Brl Trust Distribuidora De Títulos E Valores Mobiliários S.A.",
    "Broker Brasil Corretora De Câmbio Ltda.",
    "Bs2 Distribuidora De Títulos E Valores Mobiliários S.A.",
    "Cambionet Corretora De Câmbio Ltda.",
    "Carol Distribuidora De Titulos E Valores Mobiliarios Ltda.",
    "Cartos Sociedade De Crédito Direto S.A.",
    "Caruana S.A. – Sociedade De Crédito",
    "Casa Do Crédito S.A. Sociedade De Crédito Ao Microempreendedor",
    "Central Cooperativa De Crédito No Estado Do Espírito Santo – Cecoop",
    "Central De Cooperativas De Economia E Crédito Mútuo Do Estado Do Rio Grande Do S",
    "China Construction Bank (Brasil) Banco Múltiplo S.A.",
    "Cielo S.A.",
    "Citibank N.A.",
    "Cm Capital Markets Corretora De Câmbio, Títulos E Valores Mobiliários Ltda",
    "Codepe Corretora De Valores E Câmbio S.A.",
    "Código Banco Beg S.A.",
    "Commerzbank Brasil S.A. – Banco Múltiplo",
    "Confidence Corretora De Câmbio S.A.",
    "Cooperativa Central De Crédito – Ailos",
    "Cooperativa de Crédito Mutuo dos Despachantes de Trânsito de Santa Catarina e Rio Grande do Sul",
    "Cooperativa De Crédito Rural Coopavel",
    "Cooperativa De Crédito Rural De Abelardo Luz – Sulcredi/Crediluz",
    "Cooperativa De Credito Rural De Ibiam – Sulcredi/Ibiam",
    "Cooperativa De Crédito Rural De Ouro Sulcredi/Ouro",
    "Cooperativa De Credito Rural De Primavera Do Leste",
    "Cooperativa De Crédito Rural De São Miguel Do Oeste – Sulcredi/São Miguel",
    "Cora Sociedade De Crédito Direto S.A.",
    "Credialiança Cooperativa De Crédito Rural",
    "Credicoamo Credito Rural Cooperativa",
    "Credisan Cooperativa De Crédito",
    "Credisis – Central De Cooperativas De Crédito Ltda.",
    "Credit Suisse Hedging-Griffo Corretora De Valores S.A",
    "Creditas Sociedade De Crédito Direto S.A.",
    "Crefaz Sociedade De Crédito Ao Microempreendedor E A Empresa De Pequeno Porte Lt",
    "Decyseo Corretora De Cambio Ltda.",
    "Deutsche Bank S.A. – Banco Alemao",
    "Easynvest – Título Corretora De Valores Sa",
    "Facta Financeira S.A. – Crédito Financiamento e Investimento",
    "Fair Corretora De Cambio S.A.",
    "Ffa Sociedade De Crédito Ao Microempreendedor E À Empresa De Pequeno Porte Ltda.",
    "Fram Capital Distribuidora De Títulos E Valores Mobiliários S.A.",
    "Frente Corretora De Câmbio Ltda.",
    "Genial Investimentos Corretora De Valores Mobiliários S.A.",
    "Goldman Sachs Banco Múltiplo S.A.",
    "Grancapital S.A. – Corretora De Títulos E Valores Mobiliários",
    "Green Card Corretora De Valores S.A.",
    "Hsbc Bank Brasil S.A. – Banco Múltiplo",
    "Itaú Corretora De Valores S.A.",
    "Jpmorgan Chase Bank N.A.",
    "J.safra S.A.",
    "Ka Financeira S.A. – Crédito, Financiamento e Investimento",
    "Lloyds Bank Brasil S.A. – Banco Múltiplo",
    "Modalmais S.A.",
    "Morgan Stanley S.A.",
    "Mtg Bank S.A.",
    "Panamericano Crédito S.A.",
    "Platinum Corretora De Câmbio Ltda.",
    "Rdb Corretora De Títulos E Valores Mobiliários Ltda.",
    "Safra Corretora De Valores S.A.",
    "Sicoob",
    "Smartbank",
    "Sxp Valores Mobiliários S.A.",
    "Tectoy Capital S.A.",
    "Tóquio Marine Seguradora S.A.",
    "Triângulo S.A.",
    "Tricury S.A.",
    "Valor Capital S.A.",
    "Votorantim Banco S.A.",
    "Westwing Bank S.A."
];